services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_projetoaula04
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Coti@2025"
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    networks:
      - coti_network
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:

networks:
  coti_network:
    driver: bridge