--SCRIPT PARA CRIAÇÃO DA TABELA DE CLIENTES
CREATE TABLE CLIENTE(
	ID					UNIQUEIDENTIFIER	PRIMARY KEY,
	NOME				VARCHAR(100)		NOT NULL,
	EMAIL				VARCHAR(50)			NOT NULL,
	DATAHORACRIACAO		DATETIME			NOT NULL,
	DATAHORAALTERACAO	DATETIME			NOT NULL,
	ATIVO				BIT					NOT NULL);